language: bash
sudo: required
os:
  - linux

jobs:
  include:
    - stage: build
      env: emacs
      script:
        - cd ./emacs/centos7
        - make
    - stage: build
      env: git
      script:
        - cd ./git/centos7
        - make
    - stage: build
      env: zsh
      script:
        - cd ./zsh/centos7
        - make
    - stage: test
      env: emacs
      script:
        - cd ./emacs/centos7
        - make test
    - stage: test
      env: git
      script:
        - cd ./git/centos7
        - make test
    - stage: test
      env: zsh
      script:
        - cd ./zsh/centos7
        - make test
